"""empty message

Revision ID: c5ea46b2f352
Revises: 310882925aa6
Create Date: 2022-05-20 01:56:05.237024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ea46b2f352'
down_revision = '310882925aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "Artist" RENAME COLUMN website TO website_link;')
    op.execute('ALTER TABLE "Venue" RENAME COLUMN website TO website_link;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "Artist" RENAME COLUMN website_link TO website;')
    op.execute('ALTER TABLE "Venue" RENAME COLUMN website_link TO website;')
    # ### end Alembic commands ###
